language: node_js
node_js: lts/*
install:
  - npm ci
script:
  - npm run build
  - npm run test
env:
  - NODE_ENV=test DB_CONNECTION_TEST=mongodb+srv://test_user:12345@cluster0.4rzgj.mongodb.net/issue_tracker_testing?retryWrites=true&w=majority JWT_SECRET=bloop
