os: linux
dist: xenial
language: node_js
node_js: lts/*
services:
  - mongodb
install:
  - npm ci
before_script:
  - mongo issue_tracker_testing --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm run build
  - npm run test
env:
  - NODE_ENV=test DB_CONNECTION_TEST=mongodb://travis:test@localhost:27017/issue_tracker_testing?retryWrites=true&w=majority JWT_SECRET=bloop
